### ISSUE TITLE
How can I use a preexisting private key?

### ISSUE THREAD

**Issue by reedog117** [Eelviny/chia-docker#4]
I already have a word mnemonic from which I can regenerate my private key. How can I use that to generate the proper keyfile for use?

**Comment by Eelviny** [comment]
In the README, check out the "generating a keyfile" section. Skip all of these steps, and instead just place the mnemonic in a file inside the farmer and plotter repositories named `keyfile`. Your structure should look like this after:

```
.
├── farmer
│   ├── Dockerfile
│   ├── farmer.sh
│   └── keyfile
├── plotter
│   ├── Dockerfile
│   ├── keyfile
│   └── plotter.sh
├── README.md
└── start-plotters.sh
```
The keyfile simply holds the mnemonic, that's it. The file will be copied into the container, and the container will ensure it's imported.
