### ISSUE TITLE
chia-docker needs to live on an SSD - volume not recommended

### ISSUE THREAD

**Issue by voycey** [Eelviny/chia-docker#5]
Thanks for creating this tool - it is nice and simple and works great on my QNAP NAS.

However there is one gotcha with this setup and that is if you have docker set up on a SATA drive / SATA RAID.

The chia-db requires extremely high iops otherwise this causes out of sync problems to occur regularly (I could never get this synced), much faster than what SATA is able to provide unless a dedicated drive (and then maybe even not enough).

Docker doesn't make it that easy to move a single volume to a different drive - you usually have to move the entire docker container storage.

For others having the same issue you have to not create a volume and instead create a folder on the host on an SSD drive different to that of the plotting SSD (I just used an old 128GB 2.5" SSD I had lying around).

You can then run the command like this:

docker run -it -p 8444:8444 --name farmer -v /path/to/ssd/for/chia/db/storage:/root/.chia -v /plot-storage:/plots:ro localhost/chia-farmer

And you should have no problems sync'ing everything up - Hope this helps!

**Comment by voycey** [comment]
The difference was like Night and Day after making this change - sync'd within 10 mins

![image](https://user-images.githubusercontent.com/1065098/118387582-8d621e00-b662-11eb-9522-748f55e25167.png)

**Comment by Eelviny** [comment]
Hi there,

No worries! Glad my setup helped out. I didn't add any information on this because in my setup, the boot drive is an NVMe SSD, and I have my Docker setup and therefore my volume living there too.

What I'll do is add some information about the chia-db needing a drive with good IOPS, but in the end it's up to the user on how they mount their volumes.

**Comment by voycey** [comment]
I think for the most part this is compounded by the problems that 1.1.5 is having with synchronisation, especially for my NAS setup (which I would imagine many people are using) - Docker gets installed on the main drive, didn't even imagine this would be a problem prior to encountering the inability to sync (and no meaningful errors from Chia or Docker on it). 
Docs will hopefully help people avoid the same issue I had :) 

Thanks again!
