### ISSUE TITLE
location of logs?

### ISSUE THREAD

**Issue by gurkburk76** [Eelviny/chia-docker#6]
Trying to use this https://github.com/stolk/chiaplotgraph to graph the logs, but unsure to where/if the logs that are needed at all are written to disk.
The same author also has a gfx for farming that does work well with your docker image after some additions to the logfile :)

**Comment by Eelviny** [comment]
Hey! Sure, I can give some pointers.

I took a look at the tool you gave a link to, and from what I see, it takes a file from the output of the plotter. In my implementation, the logs of each plotter are stored by Docker and available when you do `docker logs plotter1`.

If you perform this command: `docker inspect --format='{{.LogPath}}' plotter1` it'll give you the location of the actual file that Docker stores the logs in. Hopefully you can point the tool at that!

You can even take that a step further:
``` bash
./chiaplotgraph $(docker inspect --format='{{.LogPath}}' plotter1) $(docker inspect --format='{{.LogPath}}' plotter2)
```
This will automatically resolve the path to each file, then pass it to the chiaplotgraph command.
